/* Generated by Kobel Bootstrap Compiler v1 */
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>

typedef struct Point Point;

struct Point {
    int32_t x;
    int32_t y;
};

int32_t add(int32_t a, int32_t b);
int32_t main(void);

int32_t add(int32_t a, int32_t b) {
    return (a + b);
}

int32_t main(void) {
    Point p = (Point){ 10, 20 };
    int32_t total = add((p).x, (p).y);
    return total;
}

