<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Kobel</string>
	<key>scopeName</key>
	<string>source.kobel</string>
	<key>fileTypes</key>
	<array>
		<string>kb</string>
		<string>kobel</string>
	</array>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#characters</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enums</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum-access</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#member-access</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#declarations</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special-types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#generics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#function-calls</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>comment.line</string>
					<key>match</key>
					<string>//.*$</string>
				</dict>
				<dict>
					<key>name</key>
					<string>comment.block</string>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>string</string>
				<key>begin</key>
				<string>&quot;</string>
				<key>end</key>
				<string>&quot;</string>
				<key>patterns</key>
				<array>
					<dict>
						<key>name</key>
						<string>constant.character.escape</string>
						<key>match</key>
						<string>\\(?:[\\&quot;&apos;nrt0$]|x[0-9a-fA-F]{2}|u[0-9a-fA-F]{4})</string>
					</dict>
					<dict>
						<key>name</key>
						<string>meta.template.expression</string>
						<key>begin</key>
						<string>\$\{</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\}</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation</string>
							</dict>
						</dict>
						<key>patterns</key>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</dict>
				</array>
			</dict>
		</dict>
		<key>characters</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>string</string>
				<key>match</key>
				<string>&apos;(?:\\[\\&quot;&apos;nrt0]|[^&apos;\\])&apos;</string>
			</dict>
		</dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>entity.other.attribute-name</string>
				<key>match</key>
				<string>@(?:operator|infix|[a-zA-Z_][a-zA-Z0-9_]*)</string>
			</dict>
		</dict>
		<key>enums</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>meta.enum</string>
				<key>begin</key>
				<string>(?:\b(pub)\s+)?\b(enum)\s+([a-zA-Z_][a-zA-Z0-9_]*)(?:\s*(:)\s*([a-zA-Z_][a-zA-Z0-9_]*))?\s*(\{)</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>keyword</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.class</string>
					</dict>
					<key>4</key>
					<dict>
						<key>name</key>
						<string>punctuation</string>
					</dict>
					<key>5</key>
					<dict>
						<key>name</key>
						<string>support.type entity.name.class</string>
					</dict>
					<key>6</key>
					<dict>
						<key>name</key>
						<string>punctuation</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\}</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation</string>
					</dict>
				</dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#comments</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#numbers</string>
					</dict>
					<dict>
						<key>name</key>
						<string>constant</string>
						<key>match</key>
						<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b(?=\s*(?:=|,|\}|//|/\*|$))</string>
					</dict>
					<dict>
						<key>include</key>
						<string>$self</string>
					</dict>
				</array>
			</dict>
		</dict>
		<key>enum-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b([A-Z][a-zA-Z0-9_]*)\s*(\.)\s*([a-zA-Z_][a-zA-Z0-9_]*)\b(?=\s*[^\(\w]|$)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>constant</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>name</key>
					<string>constant</string>
					<key>match</key>
					<string>\b[A-Z][A-Z0-9_]{1,}\b</string>
				</dict>
			</array>
		</dict>
		<key>member-access</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self)\s*(\.)\s*([a-zA-Z_][a-zA-Z0-9_]*)\s*(?=\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(self)\s*(\.)\s*([a-zA-Z_][a-zA-Z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>variable.other.property.kobel</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>declarations</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(fn)\s+([a-zA-Z_][a-zA-Z0-9_]*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name.function</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(mod)\s+([a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)*)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name</string>
						</dict>
					</dict>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(use)\s+([a-zA-Z_][a-zA-Z0-9_]*(?:\.[a-zA-Z_][a-zA-Z0-9_]*)*(?:\.\*)?)</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.name</string>
						</dict>
					</dict>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>keyword</string>
				<key>match</key>
				<string>\b(val|var|const|pub|extern|if|else|when|for|in|while|loop|break|continue|return|yield|defer|as\?|as|null|true|false|self|impl|struct|trait|fault|alias|fn)\b</string>
			</dict>
		</dict>
		<key>special-types</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>entity.name.function</string>
				<key>match</key>
				<string>\b(List|Iterable|Self)\b</string>
			</dict>
		</dict>
		<key>generics</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?&lt;=[a-zA-Z0-9_])&lt;(?=[a-zA-Z0-9_&amp;*,\s&lt;&gt;]+&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
					</dict>
					<key>end</key>
					<string>&gt;</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#primitive-types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#special-types</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#generics</string>
						</dict>
						<dict>
							<key>name</key>
							<string>entity.name.type.parameter.kobel</string>
							<key>match</key>
							<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b</string>
						</dict>
						<dict>
							<key>name</key>
							<string>punctuation</string>
							<key>match</key>
							<string>[,&amp;*]</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.type.parameter.kobel</string>
					<key>match</key>
					<string>\b[A-Z]\b</string>
				</dict>
			</array>
		</dict>
		<key>primitive-types</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>support.type</string>
				<key>match</key>
				<string>\b(i8|i16|i32|i64|isz|u8|u16|u32|u64|usz|f16|f32|f64|bool|char|str|none)\b</string>
			</dict>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#primitive-types</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
					<key>match</key>
					<string>\b(Array|Slice|Map|HashMap|Pair)\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>entity.name.class</string>
					<key>match</key>
					<string>\b[A-Z][a-zA-Z0-9_]*\b</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>\b0[xX][0-9a-fA-F_]+(?:_?(?:US|UL|UB|UZ|U|S|L|B|Z))?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>\b0[bB][01_]+(?:_?(?:US|UL|UB|UZ|U|S|L|B|Z))?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>\b0[oO][0-7_]+(?:_?(?:US|UL|UB|UZ|U|S|L|B|Z))?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>\b[0-9][0-9_]*\.[0-9][0-9_]*(?:[eE][+-]?[0-9_]+)?(?:[FD])?\b</string>
				</dict>
				<dict>
					<key>name</key>
					<string>constant.numeric</string>
					<key>match</key>
					<string>\b[0-9][0-9_]*(?:_?(?:US|UL|UB|UZ|U|S|L|B|Z|F|D))?\b</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(=&gt;|-&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(\.\.&lt;|&gt;\.\.&lt;|\.\.)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(\?:|!:)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(==|!=|&lt;=|&gt;=|&lt;|&gt;)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(&amp;&amp;|\|\||!)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(\+=|-=|\*=|/=|%=|=)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(\+\+|--|\+|-|\*|/|%)</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
					<key>match</key>
					<string>(&amp;|\|\|?|\^|~|&lt;&lt;|&gt;&gt;)</string>
				</dict>
			</array>
		</dict>
		<key>function-calls</key>
		<dict>
			<key>patterns</key>
			<dict>
				<key>name</key>
				<string>entity.name.function</string>
				<key>match</key>
				<string>\b([a-zA-Z_][a-zA-Z0-9_]*)(?=\s*(?:&lt;[^&gt;]+&gt;)?\s*\()</string>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
